export const employees = [
  {
    id: 1,
    name: "ahmad",
    f_name: "mahmod",
    g_f_name: "hamid",
    job: "IT",
    phone: 784300100,
    email: "example@gmail.com",
    education: "bachelor",
    dpt: "IT",
  },
  {
    id: 2,
    name: "ahmad",
    f_name: "mahmod",
    g_f_name: "hamid",
    job: "IT",
    phone: 784300100,
    email: "example@gmail.com",
    education: "bachelor",
    dpt: "IT",
  },
  {
    id: 3,
    name: "ahmad",
    f_name: "mahmod",
    g_f_name: "hamid",
    job: "IT",
    phone: 784300100,
    email: "example@gmail.com",
    education: "bachelor",
    dpt: "IT",
  },
  {
    id: 4,
    name: "ahmad",
    f_name: "mahmod",
    g_f_name: "hamid",
    job: "IT",
    phone: 784300100,
    email: "example@gmail.com",
    education: "bachelor",
    dpt: "IT",
  },
  {
    id: 5,
    name: "ahmad",
    f_name: "mahmod",
    g_f_name: "hamid",
    job: "IT",
    phone: 784300100,
    email: "example@gmail.com",
    education: "bachelor",
    dpt: "IT",
  },
  {
    id: 6,
    name: "ahmad",
    f_name: "mahmod",
    g_f_name: "hamid",
    job: "IT",
    phone: 784300100,
    email: "example@gmail.com",
    education: "bachelor",
    dpt: "IT",
  },
  {
    id: 7,
    name: "ahmad",
    f_name: "mahmod",
    g_f_name: "hamid",
    job: "IT",
    phone: 784300100,
    email: "example@gmail.com",
    education: "bachelor",
    dpt: "IT",
  },
  {
    id: 8,
    name: "ahmad",
    f_name: "mahmod",
    g_f_name: "hamid",
    job: "IT",
    phone: 784300100,
    email: "example@gmail.com",
    education: "bachelor",
    dpt: "IT",
  },
  {
    id: 9,
    name: "ahmad",
    f_name: "mahmod",
    g_f_name: "hamid",
    job: "IT",
    phone: 784300100,
    email: "example@gmail.com",
    education: "bachelor",
    dpt: "IT",
  },
];

export const employeesAttendence = [
  {
    id: 1,
    name: "Snow",
    departement: "Jon",
    job: "IT",
    present_absent: "Absent",
  },
  {
    id: 2,
    name: "Lannister",
    departement: "Cersei",
    job: "IT",
    present_absent: "Absent",
  },
  {
    id: 3,
    name: "Lannister",
    departement: "Jaime",
    job: "IT",
    present_absent: "Absent",
  },
  {
    id: 4,
    name: "Stark",
    departement: "Arya",
    job: "IT",
    present_absent: "Absent",
  },
  {
    id: 5,
    name: "Targaryen",
    departement: "Daenerys",
    job: "IT",
    present_absent: "Absent",
  },
  {
    id: 6,
    name: "Melisandre",
    departement: "IT",
    job: "IT",
    present_absent: "Absent",
  },
  {
    id: 7,
    name: "Clifford",
    departement: "Ferrara",
    job: "IT",
    present_absent: "Absent",
  },
  {
    id: 8,
    name: "Frances",
    departement: "Rossini",
    job: "IT",
    present_absent: "Absent",
  },
  {
    id: 9,
    name: "Roxie",
    departement: "Harvey",
    job: "IT",
    present_absent: "Absent",
  },
];

export const GOVPumpStation = [
  {
    id: 1,
    license_number: "k1f182022",
    tank_name: "Ahmadyar",
    owner: "IDK",
    location: "Macrorayan",
    phone_number: "0784300001",
    ipg_gun: "4",
    petrol_gun: "10",
    desal_gun: "5",
    tax: "0.2",
  },
  {
    id: 2,
    license_number: "k1f182022",
    tank_name: "Ahmadyar",
    owner: "IDK",
    location: "Macrorayan",
    phone_number: "0784300001",
    ipg_gun: "4",
    petrol_gun: "10",
    desal_gun: "5",
    tax: "0.2",
  },
  {
    id: 3,
    license_number: "k1f182022",
    tank_name: "Ahmadyar",
    owner: "IDK",
    location: "Macrorayan",
    phone_number: "0784300001",
    ipg_gun: "4",
    petrol_gun: "10",
    desal_gun: "5",
    tax: "0.2",
  },
  {
    id: 4,
    license_number: "k1f182022",
    tank_name: "Ahmadyar",
    owner: "IDK",
    location: "Macrorayan",
    phone_number: "0784300001",
    ipg_gun: "4",
    petrol_gun: "10",
    desal_gun: "5",
    tax: "0.2",
  },
  {
    id: 5,
    license_number: "k1f182022",
    tank_name: "Ahmadyar",
    owner: "IDK",
    location: "Macrorayan",
    phone_number: "0784300001",
    ipg_gun: "4",
    petrol_gun: "10",
    desal_gun: "5",
    tax: "0.2",
  },
  {
    id: 6,
    license_number: "k1f182022",
    tank_name: "Ahmadyar",
    owner: "IDK",
    location: "Macrorayan",
    phone_number: "0784300001",
    ipg_gun: "4",
    petrol_gun: "10",
    desal_gun: "5",
    tax: "0.2",
  },
  {
    id: 7,
    license_number: "k1f182022",
    tank_name: "Ahmadyar",
    owner: "IDK",
    location: "Macrorayan",
    phone_number: "0784300001",
    ipg_gun: "4",
    petrol_gun: "10",
    desal_gun: "5",
    tax: "0.2",
  },
  {
    id: 8,
    license_number: "k1f182022",
    tank_name: "Ahmadyar",
    owner: "IDK",
    location: "Macrorayan",
    phone_number: "0784300001",
    ipg_gun: "4",
    petrol_gun: "10",
    desal_gun: "5",
    tax: "0.2",
  },
  {
    id: 9,
    license_number: "k1f182022",
    tank_name: "Ahmadyar",
    owner: "IDK",
    location: "Macrorayan",
    phone_number: "0784300001",
    ipg_gun: "4",
    petrol_gun: "10",
    desal_gun: "5",
    tax: "0.2",
  },
];

export const GOVMetterReading = [
  {
    id: 1,
    tank_name: "Ahmadyar",
    id_no: "k1f182022",
    location: "Macrorayan",
    fuel_product: "LPG",
    total_liter: 30,
    total_charges: "0.2",
  },
  {
    id: 2,
    tank_name: "Ahmadyar",
    id_no: "k1f182022",
    location: "Macrorayan",
    fuel_product: "LPG",
    total_liter: 30,
    total_charges: "0.2",
  },
  {
    id: 3,
    tank_name: "Ahmadyar",
    id_no: "k1f182022",
    location: "Macrorayan",
    fuel_product: "LPG",
    total_liter: 30,
    total_charges: "0.2",
  },
  {
    id: 4,
    tank_name: "Ahmadyar",
    id_no: "k1f182022",
    location: "Macrorayan",
    fuel_product: "LPG",
    total_liter: 30,
    total_charges: "0.2",
  },
  {
    id: 5,
    tank_name: "Ahmadyar",
    id_no: "k1f182022",
    location: "Macrorayan",
    fuel_product: "LPG",
    total_liter: 30,
    total_charges: "0.2",
  },
  {
    id: 6,
    tank_name: "Ahmadyar",
    id_no: "k1f182022",
    location: "Macrorayan",
    fuel_product: "LPG",
    total_liter: 30,
    total_charges: "0.2",
  },
  {
    id: 7,
    tank_name: "Ahmadyar",
    id_no: "k1f182022",
    location: "Macrorayan",
    fuel_product: "LPG",
    total_liter: 30,
    total_charges: "0.2",
  },
  {
    id: 8,
    tank_name: "Ahmadyar",
    id_no: "k1f182022",
    location: "Macrorayan",
    fuel_product: "LPG",
    total_liter: 30,
    total_charges: "0.2",
  },
  {
    id: 9,
    tank_name: "Ahmadyar",
    id_no: "k1f182022",
    location: "Macrorayan",
    fuel_product: "LPG",
    total_liter: 30,
    total_charges: "0.2",
  },
];

export const PRIPumpStation = [
  {
    id: 1,
    license_number: "k1f182022",
    tank_name: "Ahmadyar",
    owner: "IDK",
    location: "Macrorayan",
    phone_number: "0784300001",
    ipg_gun: "4",
    petrol_gun: "10",
    desal_gun: "5",
    tax: "0.2",
  },
  {
    id: 2,
    license_number: "k1f182022",
    tank_name: "Ahmadyar",
    owner: "IDK",
    location: "Macrorayan",
    phone_number: "0784300001",
    ipg_gun: "4",
    petrol_gun: "10",
    desal_gun: "5",
    tax: "0.2",
  },
  {
    id: 3,
    license_number: "k1f182022",
    tank_name: "Ahmadyar",
    owner: "IDK",
    location: "Macrorayan",
    phone_number: "0784300001",
    ipg_gun: "4",
    petrol_gun: "10",
    desal_gun: "5",
    tax: "0.2",
  },
  {
    id: 4,
    license_number: "k1f182022",
    tank_name: "Ahmadyar",
    owner: "IDK",
    location: "Macrorayan",
    phone_number: "0784300001",
    ipg_gun: "4",
    petrol_gun: "10",
    desal_gun: "5",
    tax: "0.2",
  },
  {
    id: 5,
    license_number: "k1f182022",
    tank_name: "Ahmadyar",
    owner: "IDK",
    location: "Macrorayan",
    phone_number: "0784300001",
    ipg_gun: "4",
    petrol_gun: "10",
    desal_gun: "5",
    tax: "0.2",
  },
  {
    id: 6,
    license_number: "k1f182022",
    tank_name: "Ahmadyar",
    owner: "IDK",
    location: "Macrorayan",
    phone_number: "0784300001",
    ipg_gun: "4",
    petrol_gun: "10",
    desal_gun: "5",
    tax: "0.2",
  },
  {
    id: 7,
    license_number: "k1f182022",
    tank_name: "Ahmadyar",
    owner: "IDK",
    location: "Macrorayan",
    phone_number: "0784300001",
    ipg_gun: "4",
    petrol_gun: "10",
    desal_gun: "5",
    tax: "0.2",
  },
  {
    id: 8,
    license_number: "k1f182022",
    tank_name: "Ahmadyar",
    owner: "IDK",
    location: "Macrorayan",
    phone_number: "0784300001",
    ipg_gun: "4",
    petrol_gun: "10",
    desal_gun: "5",
    tax: "0.2",
  },
  {
    id: 9,
    license_number: "k1f182022",
    tank_name: "Ahmadyar",
    owner: "IDK",
    location: "Macrorayan",
    phone_number: "0784300001",
    ipg_gun: "4",
    petrol_gun: "10",
    desal_gun: "5",
    tax: "0.2",
  },
];

export const PRIMetterReading = [
  {
    id: 1,
    tank_name: "Ahmadyar",
    id_no: "k1f182022",
    location: "Macrorayan",
    fuel_product: "LPG",
    total_liter: 30,
    total_charges: "0.2",
  },
  {
    id: 2,
    tank_name: "Ahmadyar",
    id_no: "k1f182022",
    location: "Macrorayan",
    fuel_product: "LPG",
    total_liter: 30,
    total_charges: "0.2",
  },
  {
    id: 3,
    tank_name: "Ahmadyar",
    id_no: "k1f182022",
    location: "Macrorayan",
    fuel_product: "LPG",
    total_liter: 30,
    total_charges: "0.2",
  },
  {
    id: 4,
    tank_name: "Ahmadyar",
    id_no: "k1f182022",
    location: "Macrorayan",
    fuel_product: "LPG",
    total_liter: 30,
    total_charges: "0.2",
  },
  {
    id: 5,
    tank_name: "Ahmadyar",
    id_no: "k1f182022",
    location: "Macrorayan",
    fuel_product: "LPG",
    total_liter: 30,
    total_charges: "0.2",
  },
  {
    id: 6,
    tank_name: "Ahmadyar",
    id_no: "k1f182022",
    location: "Macrorayan",
    fuel_product: "LPG",
    total_liter: 30,
    total_charges: "0.2",
  },
  {
    id: 7,
    tank_name: "Ahmadyar",
    id_no: "k1f182022",
    location: "Macrorayan",
    fuel_product: "LPG",
    total_liter: 30,
    total_charges: "0.2",
  },
  {
    id: 8,
    tank_name: "Ahmadyar",
    id_no: "k1f182022",
    location: "Macrorayan",
    fuel_product: "LPG",
    total_liter: 30,
    total_charges: "0.2",
  },
  {
    id: 9,
    tank_name: "Ahmadyar",
    id_no: "k1f182022",
    location: "Macrorayan",
    fuel_product: "LPG",
    total_liter: 30,
    total_charges: "0.2",
  },
];

export const borders = [
  // {
  //   id: 1,
  //   company_name: "Ahmadyar",
  //   license_number: "k1f182022",
  //   owner: "IDK",
  //   product: "LPG",
  //   import: "IDK",
  //   quality_test: "a95",
  //   income: "20ton a80",
  //   tax: "0.2",
  // },
  {
    id: 1,
    company_name: "Ahmadyar",
    owner: "IDK",
    product: "LPG",
    import: "IDK",
    export: "IDK",
    tax: "0.2",
  },
  {
    id: 2,
    company_name: "Ahmadyar",
    owner: "IDK",
    product: "LPG",
    import: "IDK",
    export: "IDK",
    tax: "0.2",
  },
  {
    id: 3,
    company_name: "Ahmadyar",
    owner: "IDK",
    product: "LPG",
    import: "IDK",
    export: "IDK",
    tax: "0.2",
  },
  {
    id: 4,
    company_name: "Ahmadyar",
    owner: "IDK",
    product: "LPG",
    import: "IDK",
    export: "IDK",
    tax: "0.2",
  },
  {
    id: 5,
    company_name: "Ahmadyar",
    owner: "IDK",
    product: "LPG",
    import: "IDK",
    export: "IDK",
    tax: "0.2",
  },
  {
    id: 6,
    company_name: "Ahmadyar",
    owner: "IDK",
    product: "LPG",
    import: "IDK",
    export: "IDK",
    tax: "0.2",
  },
  {
    id: 7,
    company_name: "Ahmadyar",
    owner: "IDK",
    product: "LPG",
    import: "IDK",
    export: "IDK",
    tax: "0.2",
  },
  {
    id: 8,
    company_name: "Ahmadyar",
    owner: "IDK",
    product: "LPG",
    import: "IDK",
    export: "IDK",
    tax: "0.2",
  },
  {
    id: 9,
    company_name: "Ahmadyar",
    owner: "IDK",
    product: "LPG",
    import: "IDK",
    export: "IDK",
    tax: "0.2",
  },
];

export const services = [
  // {
  //   id: 1,
  //   license_number: "k1f182022",
  //   owner: "IDK",
  //   location: "Macrorayan",
  //   fuel_product: "IDK",
  //   // ipg_gun: "4",
  //   // petrol_gun: "10",
  //   // desal_gun: "5",
  //   tax: "0.2",
  // },
  {
    id: 1,
    company_name: "Ahmadyar",
    owner: "IDK",
    reserve: "5 liter",
    tax: "0.2",
    ton:5
  },
  {
    id: 2,
    company_name: "Ahmadyar",
    owner: "IDK",
    reserve: "5 liter",
    tax: "0.2",
    ton:5
  },
  {
    id: 3,
    company_name: "Ahmadyar",
    owner: "IDK",
    reserve: "5 liter",
    tax: "0.2",
    ton:5
  },
  {
    id: 4,
    company_name: "Ahmadyar",
    owner: "IDK",
    reserve: "5 liter",
    tax: "0.2",
    ton:5
  },
  {
    id: 5,
    company_name: "Ahmadyar",
    owner: "IDK",
    reserve: "5 liter",
    tax: "0.2",
    ton:5
  },
  {
    id: 6,
    company_name: "Ahmadyar",
    owner: "IDK",
    reserve: "5 liter",
    tax: "0.2",
    ton:5
  },
  {
    id: 7,
    company_name: "Ahmadyar",
    owner: "IDK",
    reserve: "5 liter",
    tax: "0.2",
    ton:5
  },
  {
    id: 8,
    company_name: "Ahmadyar",
    owner: "IDK",
    reserve: "5 liter",
    tax: "0.2",
    ton:5
  },
  {
    id: 9,
    company_name: "Ahmadyar",
    owner: "IDK",
    reserve: "5 liter",
    tax: "0.2",
    ton:5
  },
];
